os: linux
language: node_js
node_js:
  - "lts/*"
dist: trusty
addons:
  chrome: stable # have Travis install Chrome stable.
jobs:
  include:
    - name: "Build & Test"
      script:
        - yarn run build
        - yarn test --browser ChromeHeadless
      deploy:
        - provider: script
          script: ./publish-npm.sh
          skip_cleanup: true
          on:
            branch: master
            tags: true
            condition: "$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$"
