os: linux
language: node_js
node_js:
  - "lts/*"
dist: trusty
addons:
  chrome: stable # have Travis install Chrome stable.
jobs:
  include:
    - name: "Build & Test"
      script:
        - npm run build
        - npm test --browser ChromeHeadless
      deploy:
        - provider: script
          script: ./publish-npm.sh
          skip_cleanup: true
